package Analizador;

public enum Categoria {
	ENTERO,
	REAL,
	IDENTIFICADOR,
	CADENA_CARACTERES,
	CADENA_CARACTERES_SIN_CERRAR,
	OPERADOR_ARTIMETICO,
	PALABRA_RESERVADA,
	OPERADOR_RELACIONAL,
	OPERADOR_LOGICO,
	OPERADOR_DE_ASIGNACION,
	OPERADOR_DE_INCREMENTO_DECREMENTO,
	PARENTESIS_APERTURA_CIERRE,
	LLAVE_APERTURA_CIERRE,
	TERMINAL_FIN_SENTENCIA,
	SEPARADOR,
	HEXADECIMAL,
	COMENTARIO,
	DESCONOCIDO
}
